spring.application.name=taskmanager

server.port=8088

#POSTGRES DB CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=215382433

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update